apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  # 1 Copy of Nginx should exist at all time
  replicas: 1
  selector:
    matchLables:
      tier: frontend
  template:
    metadata:
      lables:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80